AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

  Exclude:
    - spec/**/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
